3.  Compute the outer product of 2 vectors. Eg: p=[[1,0],[0,1]] q=[[1,2],[3,4]]

In [1]:
import numpy as np
p=[[1,0],[0,1]]
q=[[1,2],[3,4]]
print("Original matrix is : ")
print(p)
print(q)
r=np.outer(p,q)
print("Outer product of two vectors :")
print(r)

Original matrix is : 
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Outer product of two vectors :
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


4.  Write a Numpy program to compute the condition number of a given matrix.

In [2]:
import numpy as np
m=np.array([[1,2],[3,4]])
print(m)
r=np.linalg.cond(m)
print("Condition number of the said matrix is : ",r)

[[1 2]
 [3 4]]
Condition number of the said matrix is :  14.933034373659268


5.  Write a Numpy program to compute the sum of the diagonal element of a given array(matrix).

In [3]:
# Method-1
import numpy as np
a=np.arange(1,17)
print(a)
b=a.reshape(4,4)
print(b)
print("Sum of the diagonal elements : ")
print(b.trace())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sum of the diagonal elements : 
34


In [4]:
# Method-2
a=np.arange(1,17)
print(a)
b=a.reshape(4,4)
print(b)
s=0
for i in range(len(b)):
  for j in range(len(b[i])):
    if i==j:
      s+=b[i][j]
print("Sum of diagonal elements : ",s)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sum of diagonal elements :  34
